version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12.14.1
    steps:
      - checkout
      - setup_remote_docker
      - run: npm install && npm run build

workflows:
  build-dep:
    jobs:
      - build
